"""PlatformIO pre-build step: gzip every file in web/ into a C header, so the
web UI ships inside the firmware (one image, and an OTA update carries the
matching UI). Output: src/app/generated/web_assets.h (not in git)."""
import gzip
import os

Import("env")  # noqa: F821  (provided by PlatformIO)

MIME = {".html": "text/html; charset=utf-8", ".js": "application/javascript", ".css": "text/css",
        ".svg": "image/svg+xml", ".png": "image/png", ".ico": "image/x-icon", ".json": "application/json"}


def build(project):
    src = os.path.join(project, "web")
    out_dir = os.path.join(project, "src", "app", "generated")
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "web_assets.h")
    files = sorted(f for f in os.listdir(src) if not f.startswith("."))
    lines = ["// Generated by tools/embed_web.py from web/. Do not edit.", "#pragma once",
             "#include <cstddef>", "#include <cstdint>", "", "namespace flapboard {", "namespace web_assets {", ""]
    table = []
    for i, name in enumerate(files):
        data = gzip.compress(open(os.path.join(src, name), "rb").read(), 9, mtime=0)
        body = ",".join(str(b) for b in data)
        lines.append("static const uint8_t k%d[] = {%s};" % (i, body))
        mime = MIME.get(os.path.splitext(name)[1], "application/octet-stream")
        table.append('  {"/%s", "%s", k%d, sizeof(k%d)},' % (name, mime, i, i))
    lines += ["", "struct Asset { const char *path; const char *mime; const uint8_t *gz; size_t len; };",
              "static const Asset kAssets[] = {"] + table + ["};", "", "}  // namespace web_assets",
              "}  // namespace flapboard", ""]
    text = "\n".join(lines)
    if not os.path.exists(out) or open(out).read() != text:
        open(out, "w").write(text)


def build_fonts(project):
    """assets/fonts/*.ttf -> src/app/generated/fonts.h (raw bytes; flapcore
    rasterises them at whatever size the layout needs)."""
    src = os.path.join(project, "assets", "fonts")
    out = os.path.join(project, "src", "app", "generated", "fonts.h")
    files = sorted(f for f in os.listdir(src) if f.endswith(".ttf"))
    lines = ["// Generated by tools/embed_web.py from assets/fonts/. Do not edit.", "#pragma once",
             "#include <cstddef>", "#include <cstdint>", "", "namespace flapboard {", "namespace fonts {", ""]
    table = []
    for i, name in enumerate(files):
        data = open(os.path.join(src, name), "rb").read()
        lines.append("alignas(4) static const uint8_t k%d[] = {%s};" % (i, ",".join(str(b) for b in data)))
        table.append('  {"%s", k%d, sizeof(k%d)},' % (os.path.splitext(name)[0], i, i))
    lines += ["", "struct Font { const char *name; const uint8_t *data; size_t len; };",
              "static const Font kFonts[] = {"] + table + ["};", "", "}  // namespace fonts",
              "}  // namespace flapboard", ""]
    text = "\n".join(lines)
    if not os.path.exists(out) or open(out).read() != text:
        open(out, "w").write(text)


def build_sounds(project):
    """sounds/device/*.wav (16-bit mono) -> src/app/generated/sounds.h as
    int16 PCM, so the sign has its clacks without an SD card."""
    import struct
    import wave
    src = os.path.join(project, "sounds", "device")
    out = os.path.join(project, "src", "app", "generated", "sounds.h")
    files = sorted(f for f in os.listdir(src) if f.endswith(".wav"))
    lines = ["// Generated by tools/embed_web.py from sounds/device/. Do not edit.", "#pragma once",
             "#include <cstdint>", "", "namespace flapboard {", "namespace sounds {", ""]
    table = []
    rate = 0
    for i, name in enumerate(files):
        with wave.open(os.path.join(src, name)) as w:
            assert w.getnchannels() == 1 and w.getsampwidth() == 2, name
            rate = w.getframerate()
            pcm = struct.unpack("<%dh" % w.getnframes(), w.readframes(w.getnframes()))
        lines.append("static const int16_t k%d[] = {%s};" % (i, ",".join(str(v) for v in pcm)))
        table.append('  {"%s", k%d, %d},' % (os.path.splitext(name)[0], i, len(pcm)))
    lines += ["", "constexpr uint32_t kRate = %d;" % rate,
              "struct Sound { const char *name; const int16_t *pcm; uint32_t frames; };",
              "static const Sound kSounds[] = {"] + table + ["};", "", "}  // namespace sounds",
              "}  // namespace flapboard", ""]
    text = "\n".join(lines)
    if not os.path.exists(out) or open(out).read() != text:
        open(out, "w").write(text)


def build_zones(project):
    """assets/zones.txt (IANA name -> POSIX TZ, from tools/make_zones.py) ->
    src/app/generated/zones.h as one string."""
    src = os.path.join(project, "assets", "zones.txt")
    out = os.path.join(project, "src", "app", "generated", "zones.h")
    data = open(src, encoding="utf-8").read()
    body = ",".join(str(b) for b in data.encode() + b"\0")
    text = "\n".join(["// Generated by tools/embed_web.py from assets/zones.txt. Do not edit.", "#pragma once",
                      "namespace flapboard {", "namespace zones {",
                      "// \"Area/City\\tPOSIX rule\\n\" lines, NUL-terminated.",
                      "static const char kZones[] = {%s};" % body, "}  // namespace zones",
                      "}  // namespace flapboard", ""])
    if not os.path.exists(out) or open(out).read() != text:
        open(out, "w").write(text)


build(env.subst("$PROJECT_DIR"))  # noqa: F821
build_zones(env.subst("$PROJECT_DIR"))  # noqa: F821
build_sounds(env.subst("$PROJECT_DIR"))  # noqa: F821
build_fonts(env.subst("$PROJECT_DIR"))  # noqa: F821
